---
sudo: required

language: python
python:
  - 3.6
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

branches:
  only:
    - /unreviewed.*/
    - /devel.*/

env:
  global:
    # yamllint disable-line rule:line-length
    - secure: "qryiNsIMwK325/34KuQLv5ce4RhtrDhmGesiFodOWgUGDmeJxrn/ankpx0Oxa+cBRz6zmBt5J5cv+hOCQ6UPQECpjovzbzTZeA0zQAWW3L40fGrQR4GgZJSEDNT/Ds9e+vXbgmdBUEVreQZAGr39S2dVRhs2DYsOVcLwmEN5/XNfvlAyGtvK4gH3mLw38Tw7buFprLlAINzTL3nSOpqdd9/Fc2Of8qd+/8hSdjKyQpRKDON1ygTWf17QrAVcdjFw8pEEfk/DPQPLrIE+PCW6o7ZY8Cg2+PjISkq9UMNYwYv6GwSIDlH3SQj7a8zEzUbQ3vVb/ViDTK4Evk1K1CmENLAquOXVxoyNqtpoaOzwQiJItfRwdty5j7WWhpMUzQ2pdodBgG8pAZzGajci+mslnGAP2sJ24xky3B2wQiD0hxAoZJImNu9s0Qd3gfyKStA+pXiTGjQJTte3ByBgQBLRK8tynrkl4xxghCp9fPnAC7JPXEdMvDDffHrN22nhtsOZcUaUF1SgjMIltyCnUh822zpt4Oi5himevzL9kT36ctUZUYjTDDNxWckmNivXoEVmJkM7ShL42XcM6of+aRg7/OahmDoORz2vp6QZUaD4xTtDRhlFSVh6Vk0WS8qhCAPaddE3C+L+ILvaYzAPSOTXsDQQattwgTxsm+jYMrXUrdw="
    # yamllint disable-line rule:line-length
    - secure: "YOh34bmRx1kHgMIb84SXxDpOhHyY9aUGyAAE2xWx2IUSwW5dY3eEkWUZBfnr8gH/rBdyp0be7nPgpnnp4YHni11p4CgI5yV1z0GKqcMR5/jPCKpJqMn8+hCqluRI3AwZ9oSa7yHcLMpaovri2oKOA9CdA71O6ODtNseAEm0mTm3/feq6S5gZjXhiL3hn0FXZnHLXNlDPb5XPX+mKPc1S+sceDHgpjYD7RIgEGUhdXaXBBjV8RnZKWx+fqOMJtLMhFezTgkM99DuoaKRxTfaF5l2UdwW0PSU8+6WqTbJ7UxzT9OMBNTIJ1xtn2rnHO05B2ImDtWeKvWR9tly175PfGhisPNwu1POnSPd02BDN4wwOhjwc8QGmKAsBhs1MnNaCO8JpKFe7h6jdCBuWSH62InbFBcl7BMbeXzM+lRFBqPZFlwCCTgkKOAlU+hAkjczobHg5X82jGaNGo97B2Sn1c4LbRctgEekHhdu+QBrBJtRSAPKr+cFlufgRm++AdZzDDwzyFnoNVcdzebMuExhB5AjwYxg9C5fs5CPz3FbYkk9q9xxweA7liqpd3eCs4VZDtRCXuCAACPKDQXvi95/zgZaApIAdChU16K4pkPl8rJWllRfU57WBpZuCXWxHUbYouCS2St2nbbzAFfBnw4xi+xQIdggB6wCFAnUq6SGtLww="

before_script:
  - sudo add-apt-repository ppa:ansible/ansible-2.6 -y
  - sudo apt-get update
  - sudo apt-get install python3-pip shellcheck ansible
  - pip3 install -r dev-requirements.txt
  - sudo pip2 install -r dev-requirements.txt
  - "./lint-all-the-files.sh"
  - "echo success"
  - "true"

script:
  - "cp aws_credentials.shippable_template aws_credentials.yml"
  - "ansible-playbook -vvvvv test-system.yml -i localhost,"
  - "behave"

after_script:
  - ./push_on_success.sh
