---
sudo: required

language: python
python:
  - 3.6
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

branches:
  only:
    - /unreviewed.*/
    - /devel.*/

env:
  global:
    # yamllint disable-line rule:line-length
    - secure: "PPeCmpX4e8d6WnrksEYXs3R7M3bjoQKqKybyBB6CzPg0U9q869t005paXJXS6Z4b0mHBvx89UMDsh8ATGO7Zs2qrmYeMgFGkOpETjp3lHnpzngHChUT2msUZvk0rEET7O/792vq97+JMqG8g1aliuNW12BKFzGrrHB4A8vwGGN498yZ1I3D9u1Gzh2sLoHGrlfdvtNuDfdk9XMngR6vGZTjvBuLug4YmGcnpmiAoUcmiDMCf4lq8jJNDx6Nq8658dkCrjF4YsHf5mVl4+ASF0MBkruMR/rZGT3FnrqUUf0cSguII3sKzdheB50QiWnX7YruEMaZbRV8JIK+746oItF8CFsedXVRr8pekCNUc6ozR7AqAFsRuRV2XFZXBbJl227lqUzeOtqsiT1jTwkvOxzDeUIHITJDYUIs3eQFrcEsnsCMbtFAwmwOB1Fz56IcimpP64tsUywgb/MtxwpRhr319Eei2jHLu1B1fommxhN9EszZrq/cluUfSFqab7+Xs2ACVhxTBoBmTor/JRVqN0BUuGujH0wAJdOJTO80y/++j5+LK2PugOTOTlwKeJmJX1oTUvc6QzIhdNornUY1nLFpGDRQzV8voAbrrRCpFD0ZUih46cpdx0haNpu7dsBMJDrtSpzDGtJ6iKgR8SLV+2usSO1LkTiGtJUPwNRr/zn4="
    # yamllint disable-line rule:line-length
    - secure: "Prrkr2Be1isepT1RIcreRr11994g3wSEhAmqmdqeKSDRuJWogYU8zTYutTokZg5p/HURw9FCf1ferWgKBYBeHi4NaxsfVcz8yckmymOn2VoFISQ7Bql4eLH3wK8uAz0nQLjto8hwJ8A60ge9NKaDW6F+UAuGyH4KHNUo79M7kypxq2h7EskWeThAprsTrjDiEULWI9IbStWYWVFRSJzZvpmeOv6XVJlT/fcSZwQXwah/s8ginVEtwVN0f09Ns1ykVj2ekleEzq5lJu761cyRHHK2IEnfpFxdx3dJCn3J6a0bswTO52xK8JMv0EkbRGR3Kr1W1RADglbwl7gQoibdH+yK1ecs48+uqK+zMe5pPK5eWJnzSVLnLbZJblofmL8GNQsKA3QVjGo2d/RhTHHPTg8zrLU0t8hYjUp9C06vb1o1a8Ob2sMlf/D2KdiJJmqtZmGU6srTnF0wqvJOjBy4aa0SOdcAjdTjWdRxOicxt9qTbUCuTfy794nTdZz/GyvrN0iKlaZ6UzMcmnvYBIfE2g8SnZNt4ryZjBJ/0i44Rfv5ETdrz8Htuotfebujbf60MqhGEjUOwnt1ifeYTTgnQwsJLHlp8n3z9+lRyVKmbKeUMaLKzCDcmDHsdfKzknQHqk+pR2eTiCLunj8bQyvKnqHb8QjJv0bHACg4eqXWS58="

before_script:
  - sudo add-apt-repository ppa:ansible/ansible-2.6 -y
  - sudo apt-get update
  - sudo apt-get install python3-pip shellcheck ansible
  - pip3 install -r dev-requirements.txt
  - sudo pip2 install -r dev-requirements.txt
  - "./lint-all-the-files.sh"
  - "echo success"
  - "true"

script:
  - "cp aws_credentials.shippable_template aws_credentials.yml"
  - "ansible-playbook -vvvvv test-system.yml -i localhost,"
  - "behave"

after_script:
  - ./push_on_success.sh
