---
sudo: required

language: python
python:
  - 3.6
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

branches:
  only:
    - /unreviewed.*/
    - /devel.*/

before_script:
  - sudo add-apt-repository ppa:ansible/ansible-2.6 -y
  - sudo apt-get update
  - sudo apt-get install python3-pip shellcheck ansible
  - pip3 install -r dev-requirements.txt
  - sudo pip2 install -r dev-requirements.txt
  - "./lint-all-the-files.sh"
  - "echo success"
  - "true"

script:
  - "cp aws_credentials.shippable_template aws_credentials.yml"
  - "ansible-playbook -vvvvv test-system.yml -i localhost,"
  - "behave"

after_script:
  - ./push_on_success.sh
