---
sudo: required

language: python
python:
  - 3.6
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

branches:
  only:
    - /unreviewed.*/
    - /devel.*/

env:
  global:
    # yamllint disable-line rule:line-length
    - secure: "qmZvQ+Tbp5XEz9jOg3rCqQ3UvtLe/Hhzep42sZn6lkeFOW020eIzm8bCgNAvc4HQnWLQGtNUENCDUtzhgmLJXmqe/rhVuKxaMvmTjzJWvEV5SdT1q+8frT1Da8NVEz5DrGTA9GQAViyfIsc2nRzGkCaMMZ75mnzJ7Ts9Ziz/Febldnm8p2qUr8O8A3mLIv2FUOsIZMMKmQpgUeIArsfhj0gyqSnvWSoQWRmJc+YycA3arZdnlxIe4XdX8sj0tg2WsUUcu9ok5KygN3bXC3zijpBnpOHSKdwbaOaFGpscUd4vSQ4oyrIFKKylEshpwsrRi/MomSaND2BCaSPzAFComaXQX3LzrvWcr+88qGpnUPchrd5E31Y1HaqujXoQmYGmnhG3Zplgk7Tt3+n+u9eBeDlnQA5dsBDdiSlfz2Op+eMEawZ8jbFvlB7sf/QWAsrtxgZwy9dqRtyRCb5nDjztS8NsKcgBISf+vj27I9AABnAC1vFQp7/qbs8M4zgdrbM4Djt7ISJzKbPU/9cR++OIOZk1CrsAVMh2GfCfKIdoOyNnizy/YRsWOx6yFsjFOI42qQ60VHVtzBBBfcHWfITu4sCOVmncdMrHCtV9r/EbUascjcKS6FWKoXYaHUVgPWzCrwHhZkVVmseBugtDsRAczK5irAlHZ1sDeH4qrIBvpKE="
    # yamllint disable-line rule:line-length
    - secure: "OChgzbT160kKppCy8lPLFq54y9ZC9iC9wS6/SWZcNNvgNYKvrCV9vr3TgTQ+a/yll/BhzMcGVIktwldb/jVfN84PgbDmMdLF/bE1w+JHPksBn198dzDabq3wcvNDuuCpLaeJhcK+euGUm4g2W7bQLNnbhuSSRsOnaaeTTgp1SGP6XXi5WA37S4riV4ihrY6TiKiCTNmwKbL8UGz6BxCwPc3kQLte1MhATn5JeI47m1nScKWDPjmr1dp+YZZekcI7MSOtCYdA7mDnZ+Yp00hfvDKh0nuo2Y2WKmsdTFpdrgospltk2aHLJXvtxNQxPhDMMF6yw+EbLFkVuBXAU0KiZ9F+3RX9D4HRUWLEJpfS93jYX067H+MZ+jjCJEJQAH75DvXKNsRC4MgytLd8ihoFngxd9h33j7pFllA6/YJN8NaE9uqKY31mKInxSB3P4f/X41sM76Q8BbiE+QeDJyb8Zp7i0u/+GSUpAlu1yprIzm2DVu2/ChB8/U61fpGN1BWM2B3V4dUvPA90AIOpLiCoub7AkFJpFSNe2EZ0jvnjLMCFurhHCTlNcEZe5CR3q5juoIFmmjm4GNnloxdl2EH8aknYUoAeCsbQ2NWPGeTRL5L6U3a4i3Oh6oeQT3dUHMbZsAspLJtnLzhxSuvNRGgNaQSjQtFkStYIeUooK26u0qE="

before_script:
  - sudo add-apt-repository ppa:ansible/ansible-2.6 -y
  - sudo apt-get update
  - sudo apt-get install python3-pip shellcheck ansible
  - pip3 install -r dev-requirements.txt
  - sudo pip2 install -r dev-requirements.txt
  - "./lint-all-the-files.sh"
  - "echo success"
  - "true"

script:
  - "cp aws_credentials.shippable_template aws_credentials.yml"
  - "ansible-playbook -vvvvv test-system.yml -i localhost,"
  - "behave"

after_script:
  - ./push_on_success.sh
