---
#
#  This is based on the lambda and lambda policy testcases out of Ansible's integration tests
#
#  As such it is licensed under the GPLv3 with copyright belonging to various including:
#
#  * Michael De La Rue
#  * William Thames
#  * The Ansible Project
#
#  Further work on this done as paid work by Michael De La Rue for paddle.com.
#


- hosts: localhost
  vars:
    aws_account_name: build
    ansible_connection: local
    lambda_name: cf-security-group-update
    lambda_function_name: cf-security-group-update
    lambda_handler: "{{lambda_name}}.lambda_handler"
    security_group_name: cloudflare_lambda_sg
    output_dir: ~/ansible_testing
    lambda_role: "arn:aws:iam::{{aws_account}}:role/cloudflare_sg_lambda"
    #    lambda_role: "arn:aws:iam::{{aws_account}}:role/service-role/cloudflare_sg_lambda"
  vars_files:
    - "aws_credentials_{{aws_account_name}}.yml"

  roles:
    - sg_lambda
