---
language: python

python:
  - 3.7

branches:
  only:
    - unreviewed
    - unreviewed2
    - devel
    - test_devel

build:
  ci:
    - sudo apt-get install python3-pip shellcheck ansible
    - pip3 install -r dev-requirements.txt
    - "./lint-all-the-files.sh"
    - "shipctl get_integration_resource_field aws_mdd accessKey"
    - "export AWS_ACCESS_KEY_ID=$(shipctl get_integration_resource_field aws_mdd accessKey)"
    - "export AWS_SECRET_ACCESS_KEY=$(shipctl get_integration_resource_field aws_mdd secretKey)"
    - "cp aws_credentials.shippable_template aws_credentials.yml"
    - "ansible-playbook -vvvvv test-system.yml -i localhost,"
    - "behave"

after_success:
  - ./push_on_success.sh

resources:
  - name: aws_mdd
    type: integration
    integration: aws_mdd

  - name: thegit
    type: gitRepo
    integration: github
    versionTemplate:
      sourceName: PaddleHQ/aws-cloudflare-secgroup

jobs:
  - name: aws-cloudflare-secgroup_runCI
    type: runCI
    steps:
      - IN: aws_mdd
        switch: false
      - IN: thegit
