---
#
#  This is based on the lambda and lambda policy testcases out of Ansible's integration tests
#
#  As such it is licensed under the GPLv3 with copyright belonging to various including:
#
#  * Michael De La Rue
#  * William Thames
#  * The Ansible Project
#
#  Further work on this done as paid work by Michael De La Rue for paddle.com.
#


- hosts: localhost
  vars_files:
    - aws_credentials.yml
  vars:
    ansible_connection: local
    lambda_name: cf-security-group-update
    lambda_function_name: cf-security-group-update-test
    lambda_handler: "{{lambda_name}}.lambda_handler"
    security_group_name: cloudflare_lambda_test_sg
    output_dir: ~/ansible_testing

  tasks:
    - name: set up AWS credentials
      block:
        - set_fact:
            aws_connection_info: &aws_connection_info
              aws_region: '{{ aws_region }}'
              aws_access_key: '{{ aws_access_key }}'
              aws_secret_key: '{{ aws_secret_key }}'
              security_token: '{{ security_token }}'
          no_log: true

    - tags:
        - given that I have a security group which is empty
      block:

        - name: delete security group if present
          ec2_group:
            name: "{{ security_group_name }}"
            state: absent
            <<: *aws_connection_info
